const Constants = {
	START_GAME: 'START_GAME',
	GENERATE_GRID: 'GENERATE_GRID',
	UPDATE_GRID: 'UPDATE_GRID',
	RESTART_GAME: 'RESTART_GAME',
	colors: {
		DEFAULT_BAR_COLOR: '#d0d0d0',
		PRIMARY_BAR_COLOR: '#2D3047',
		SECONDARY_BAR_COLOR: '#9A031E',
		DEFAULT_BOX_COLOR: '#ffffff',
		PRIMARY_BOX_COLOR: '#5DA9E9',
		SECONDARY_BOX_COLOR: '#F78764',
	},
};

export default Constants;
